# Generated by Django 4.1.9 on 2023-06-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(max_length=2000),
        ),
    ]
